### ISSUE TITLE
Another set of working pins for C3

### ISSUE THREAD

**Issue by taHC81** [BOlaerts/ESPHome-W5500-Ethernet-on-ESP32-boards#1]
Hi, just to share another set of pins for C3, not necessary to use reset pin as well.

```
ethernet:
  type: W5500
  clk_pin: GPIO4
  mosi_pin: GPIO6
  miso_pin: GPIO5
  cs_pin: GPIO07
  interrupt_pin: GPIO10
```
